[2025-04-02T21:53:19.969+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Proj.Spark_Processing manual__2025-04-02T21:52:24.042914+00:00 [queued]>
[2025-04-02T21:53:19.978+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Proj.Spark_Processing manual__2025-04-02T21:52:24.042914+00:00 [queued]>
[2025-04-02T21:53:19.979+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-02T21:53:19.991+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Spark_Processing> on 2025-04-02 21:52:24.042914+00:00
[2025-04-02T21:53:19.996+0000] {standard_task_runner.py:60} INFO - Started process 4179 to run task
[2025-04-02T21:53:19.996+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-04-02T21:53:20.001+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Weather_Proj', 'Spark_Processing', 'manual__2025-04-02T21:52:24.042914+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/Project_tasks.py', '--cfg-path', '/tmp/tmpdfa7x2p9']
[2025-04-02T21:53:20.002+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask Spark_Processing
[2025-04-02T21:53:20.058+0000] {task_command.py:423} INFO - Running <TaskInstance: Weather_Proj.Spark_Processing manual__2025-04-02T21:52:24.042914+00:00 [running]> on host f47524c1cda8
[2025-04-02T21:53:20.129+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Weather_Proj' AIRFLOW_CTX_TASK_ID='Spark_Processing' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T21:52:24.042914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-02T21:52:24.042914+00:00'
[2025-04-02T21:53:20.950+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/WeatherScripts/spark_Weather.py", line 75, in processData
    .load()
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/sql/streaming/readwriter.py", line 304, in load
    return self._df(self._jreader.load())
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Failed to find data source: kafka. Please deploy the application as per the deployment section of Structured Streaming + Kafka Integration Guide.
[2025-04-02T21:53:20.967+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Weather_Proj, task_id=Spark_Processing, execution_date=20250402T215224, start_date=20250402T215319, end_date=20250402T215320
[2025-04-02T21:53:20.981+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task Spark_Processing (Failed to find data source: kafka. Please deploy the application as per the deployment section of Structured Streaming + Kafka Integration Guide.; 4179)
[2025-04-02T21:53:21.014+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-02T21:53:21.043+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
