[2025-04-02T22:00:02.903+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Proj.Produce_data manual__2025-04-02T21:59:57.019100+00:00 [queued]>
[2025-04-02T22:00:02.917+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Proj.Produce_data manual__2025-04-02T21:59:57.019100+00:00 [queued]>
[2025-04-02T22:00:02.917+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-02T22:00:02.933+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Produce_data> on 2025-04-02 21:59:57.019100+00:00
[2025-04-02T22:00:02.939+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-04-02T22:00:02.943+0000] {standard_task_runner.py:60} INFO - Started process 5704 to run task
[2025-04-02T22:00:02.951+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Weather_Proj', 'Produce_data', 'manual__2025-04-02T21:59:57.019100+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/Project_tasks.py', '--cfg-path', '/tmp/tmp4itzzqc1']
[2025-04-02T22:00:02.952+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask Produce_data
[2025-04-02T22:00:03.017+0000] {task_command.py:423} INFO - Running <TaskInstance: Weather_Proj.Produce_data manual__2025-04-02T21:59:57.019100+00:00 [running]> on host f47524c1cda8
[2025-04-02T22:00:03.102+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Weather_Proj' AIRFLOW_CTX_TASK_ID='Produce_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T21:59:57.019100+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-02T21:59:57.019100+00:00'
[2025-04-02T22:01:08.616+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-02T22:01:08.619+0000] {process_utils.py:131} INFO - Sending 15 to group 5704. PIDs of all processes in the group: [5704]
[2025-04-02T22:01:08.620+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 5704
[2025-04-02T22:01:08.620+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-02T22:01:08.672+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5704, status='terminated', exitcode=0, started='22:00:02') (5704) terminated with exit code 0
