[2025-04-02T20:19:29.226+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Weather_Proj.Produce_data scheduled__2025-04-02T19:20:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
