[2025-04-02T22:46:41.410+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Proj.Spark_Processing manual__2025-04-02T22:45:01.306687+00:00 [queued]>
[2025-04-02T22:46:41.420+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Proj.Spark_Processing manual__2025-04-02T22:45:01.306687+00:00 [queued]>
[2025-04-02T22:46:41.420+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-02T22:46:41.432+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Spark_Processing> on 2025-04-02 22:45:01.306687+00:00
[2025-04-02T22:46:41.438+0000] {standard_task_runner.py:60} INFO - Started process 1102 to run task
[2025-04-02T22:46:41.441+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Weather_Proj', 'Spark_Processing', 'manual__2025-04-02T22:45:01.306687+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/Project_tasks.py', '--cfg-path', '/tmp/tmp5vq9j7l7']
[2025-04-02T22:46:41.442+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask Spark_Processing
[2025-04-02T22:46:41.485+0000] {task_command.py:423} INFO - Running <TaskInstance: Weather_Proj.Spark_Processing manual__2025-04-02T22:45:01.306687+00:00 [running]> on host 520607ad0646
[2025-04-02T22:46:41.546+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Weather_Proj' AIRFLOW_CTX_TASK_ID='Spark_Processing' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T22:45:01.306687+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-02T22:45:01.306687+00:00'
[2025-04-02T22:46:41.548+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/WeatherScripts/spark_Weather.py", line 11, in processData
    .config("spark.jars.packages",
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/sql/session.py", line 276, in config
    for (k, v) in conf.getAll():
AttributeError: 'str' object has no attribute 'getAll'
[2025-04-02T22:46:41.558+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Weather_Proj, task_id=Spark_Processing, execution_date=20250402T224501, start_date=20250402T224641, end_date=20250402T224641
[2025-04-02T22:46:41.570+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task Spark_Processing ('str' object has no attribute 'getAll'; 1102)
[2025-04-02T22:46:41.613+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-02T22:46:41.641+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
